services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EmailizrBundle\Twig\Extension\InlineStyleExtension:
        tags:
            - { name: twig.extension }