imports:
    - { resource: services/*.yml }

services:

    emailizr.library.inky:
       class: Hampe\Inky\Inky
       shared: false

    emailizr.library.emogrifier:
        class: Pelago\Emogrifier
        shared: false

    emailizr.parser.email.inky_parser:
        class: EmailizrBundle\Parser\InkyParser
        arguments:
            - '@emailizr.library.inky'
            - '@pimcore.service.request.editmode_resolver'

    emailizr.parser.email.inline_style_parser:
        class: EmailizrBundle\Parser\InlineStyleParser
        arguments:
            - '@emailizr.library.emogrifier'
            - '@pimcore.service.request.editmode_resolver'

    emailizr.service.content:
        class: EmailizrBundle\Service\ContentService
        arguments:
            - '@file_locator'
            - '@emailizr.parser.email.inky_parser'
            - '@emailizr.parser.email.inline_style_parser'